name: Collect Bing.com daily images

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Scala 2.13.2
      run: |
        wget https://downloads.lightbend.com/scala/2.13.2/scala-2.13.2.deb
        sudo dpkg -i scala-2.13.2.deb && sudo apt install -f
        scala --version
        
    - name: Download image
      run: scala download.scala

    - name: Upadte README
      run: |
        image=`ls -t images/*.jpg | head -1`
        echo latest image is $image
        sed -i "s/last update:.*/last update:`date +"%F %H:%M:%S"` UTC/g" README.md
        sed -i "s#\!\[\](images/.*)#\!\[\]($image)#g" README.md

    - name: Commit
      run: |
        git config user.name counter2015
        git config user.email voidcounter@gmail.com
        git status
        git add images/*.jpg README.md
        git commit -m "auto commit from github actions" 
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
